baseURL: 'https://holzhandwerk.work'
languageCode: 'en-us'
title: 'Holzhandwerk Gantenbein'
theme: 'pikoAdv'
params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Simon + Carina Gantenbein / Christian Güdemann
  description: Your website description
  math: false
  images:
  - "/pictures/Simon_in_Action.jpeg"
  label:
    title: .WORK
    text: Holzhandwerk Gantenbein, Leidenschaft für Holz
    icon: /pictures/Logo_Holzhandwerk_Gantenbein.png
    iconHeight: "200"
    iconWIdth: "400"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: /uploads/zap.svg
    favicon16x16: /uploads/zap.svg
    favicon32x32: /uploads/zap.svg
    apple_touch_icon: /uploads/zap.svg
    safari_pinned_tab: /uploads/zap.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: Simon Gantenbein - Ihr Schreiner
    heroDescription: |
      Seit Kindertagen liebe ich es mit Holz zuarbeiten und verschiedene Dinge auszuprobieren. In der Oberstufe beispielsweise habe ich mir ein Pult selbst gebaut und bin in meiner Freizeit die Schreinerei Bantli, um es umzusetzen. In derselben ich später meine Ausbildung als Schreiner EFZ absolvierte und weitere Jahre arbeitete. 
      Neben meiner Tätigkeit als Pastor mit Schwerpunkt Jugend in der FEG Effretikon arbeite ich nun selbständig als Schreiner. Gerne stehe ich Ihnen für unterschiedliche Dienste zur Verfügung.
    heroCTAPrimaryText: Projekte
    heroCTAPrimaryUrl: "/projekte/"
    heroCTASecondaryText: Kontaktiere Mich
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/pictures/Simon_in_action.jpeg"
    # Blog Section
    disableBlogSection: true
    blogTitle: Latest Posts
    blogDescription: This is my latest blog posts
    seeMoreText: More Posts
    # About Section    
    disableAboutSection: false
    aboutTitle: Tätigkeiten
    aboutDescription: Das kann ich gut
    aboutImgUrl: "/uploads/self.webp"
    aboutContent: Hi guys. This is where you put something about yourself.
    # Portfolio Section
    disablePortfolioSection: false
    portfolioTitle: Projekte
    portfolioDescription: Eine Auswahl von Projekten
    portfolio:
    - imageUrl: /pictures/Schaukel.png
      alt: # image alt for better SEO
      description: Eine neue Schaukel.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-2.webp
      alt: # image alt for better SEO
      description: Sanierung Treppe.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-3.webp
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Blog
    title: Blog
    pre: pen-tool
    url: "/blog"
    weight: "20"
  - name: Search
    title: Search
    pre: search
    url: "/search"
    weight: "30"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
  - name: Github
    title: 
    pre: github
    url: https://github.com/heksagonnet/piko
    weight: "50"
  search: # Search page's quick links
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"
